[workspace]
authors = ["Ryan <18477649+Ryul0rd@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "vulkan-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
bindgen = "python3 bindgen.py"
package = "mojo package vk -o vk.mojopkg"
build = {depends-on = ["bindgen", "package"]}

[build-dependencies]
mojo = "==0.26.2.0.dev2026021605"
python = ">=3.10,<3.11"

[host-dependencies]
mojo = ">=0.26.2.0.dev2026012822,<0.27"
