[workspace]
authors = ["Ryan <18477649+Ryul0rd@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "vulkan-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
bindgen = "python3 bindgen.py"
package = "mojo package vk -o vk.mojopkg"
build = {depends-on = ["bindgen", "package"]}

[build-dependencies]
max = "==26.1.0.dev2025120805"
python = ">=3.10,<3.11"

[host-dependencies]
max = ">=26.1.0.dev2025120805,<26"
